# Generated by Django 5.2.1 on 2025-06-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimentation', '0001_initial'),
        ('stock', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentations',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='stock.stock', verbose_name='Número de série'),
        ),
        migrations.AddField(
            model_name='movimentations',
            name='movimentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentation', to='movimentation.movimentation_type', verbose_name='Tipo de movimentação'),
        ),
        migrations.AddField(
            model_name='movimentations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Usuário'),
        ),
    ]
