# Generated by Django 5.2.1 on 2025-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentation', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentation_type',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Tipos de movimentação'},
        ),
        migrations.AlterModelOptions(
            name='movimentations',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
    ]
