# Generated by Django 5.2.1 on 2025-06-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentation', '0003_alter_movimentation_type_options_and_more'),
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Usuário'),
        ),
    ]
