# Generated by Django 5.2.1 on 2025-06-06 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentation', '0004_alter_movimentations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentations',
            name='local',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Localidade'),
            preserve_default=False,
        ),
    ]
