# Generated by Django 5.2.4 on 2025-12-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentation', '0006_alter_movimentations_user'),
        ('stock', '0007_remove_stock_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentations',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentations', to='stock.stock', verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='movimentations',
            name='movimentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentations', to='movimentation.movimentation_type', verbose_name='Tipo de movimentação'),
        ),
    ]
