# Generated by Django 5.2.4 on 2026-02-02 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentation', '0007_alter_movimentations_item_and_more'),
        ('stock', '0007_remove_stock_custom_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentation_type',
            options={'verbose_name': 'Tipo de Movimentação', 'verbose_name_plural': 'Tipos de movimentação'},
        ),
        migrations.RemoveField(
            model_name='movimentation_type',
            name='movimentation_name',
        ),
        migrations.AddField(
            model_name='movimentation_type',
            name='code',
            field=models.CharField(default='', max_length=20,  verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='movimentation_type',
            name='description',
            field=models.CharField(default='', max_length=50, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='movimentations',
            name='moviment_flow',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default=1, max_length=3, verbose_name='Fluxo de movimentação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentations',
            name='new_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.status_item', verbose_name='Novo status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentations',
            name='previou_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.status_item', verbose_name='Status anterior'),
        ),
        migrations.AlterField(
            model_name='movimentations',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.locals', verbose_name='Localidade'),
        ),
    ]
