# Generated by Django 5.2.4 on 2026-02-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentation', '0008_alter_movimentation_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentation_type',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Código'),
        ),
    ]
