# Generated by Django 5.2.4 on 2026-02-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentation', '0009_alter_movimentation_type_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentations',
            old_name='previou_status',
            new_name='previous_status',
        ),
    ]
