# Generated by Django 5.2.1 on 2025-06-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipament_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipament_type', models.CharField(max_length=25, unique=True, verbose_name='Tipo do equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Item_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25, unique=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25, unique=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serail_number', models.CharField(max_length=40, unique=True, verbose_name='Número de série')),
                ('property_number', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Patrimônio')),
                ('request_unit', models.CharField(blank=True, default='703', max_length=10, null=True, verbose_name='Unidade solicitante')),
                ('pay_unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade pagante')),
                ('warranty', models.DateField(blank=True, null=True, verbose_name='Garantia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizaddo em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_category', to='stock.item_category', verbose_name='Categoria')),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_nota', to='invoice.invoice_item', verbose_name='Nota fiscal')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipament', to='stock.equipament_type', verbose_name='Tipo de equipamento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.locals', verbose_name='Localidade')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_item', to='stock.status_item', verbose_name='Status do item')),
            ],
        ),
    ]
