# Generated by Django 5.2.1 on 2025-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipament_type',
            options={'verbose_name_plural': 'Tipos de equipamento'},
        ),
        migrations.AlterModelOptions(
            name='item_category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='locals',
            options={'verbose_name': 'Localidade', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='status_item',
            options={'verbose_name_plural': 'Tipos de status'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='serail_number',
            new_name='serial_number',
        ),
    ]
