# Generated by Django 5.2.4 on 2025-08-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_proposal'),
        ('stock', '0002_alter_equipament_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='item_nota', to='invoice.invoice_item', verbose_name='Item da nota'),
            preserve_default=False,
        ),
    ]
