# Generated by Django 5.2.4 on 2025-09-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_invoice_number_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='custom_id',
            field=models.CharField(default='TEST-0', max_length=10, unique=False),
        ),
    ]
