# Generated by Django 5.2.4 on 2025-09-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='custom_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
