# Generated by Django 5.2.4 on 2025-12-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stock_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='custom_id',
        ),
    ]
