# Generated by Django 5.2.1 on 2025-05-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contract', models.CharField(max_length=50, unique=True, verbose_name='Numero do Contrato')),
                ('contract_name', models.CharField(max_length=50, verbose_name='Nome do contrato')),
                ('start_date', models.DateField(verbose_name='Data de Inicio')),
                ('end_date', models.DateField(verbose_name='Data de Termino')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_proposal', models.CharField(max_length=30, unique=True, verbose_name='Numero da proposta')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizaddo em')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratcs', to='contract.contract', verbose_name='Numero do contrato')),
            ],
        ),
    ]
