# Generated by Django 5.2.1 on 2025-06-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number_contract',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do contrato'),
        ),
    ]
