# Generated by Django 5.2.1 on 2025-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name_plural': 'Propostas'},
        ),
    ]
