# Generated by Django 5.2.1 on 2025-06-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_options_alter_proposal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratcs', to='contract.contract', verbose_name='Nome do contrato'),
        ),
    ]
