# Generated by Django 5.2.4 on 2025-09-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_proposal_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_registred',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
