# Generated by Django 5.2.4 on 2025-09-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_proposal_is_registred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='is_registred',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
