# Generated by Django 5.2.4 on 2025-09-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_proposal_is_registred'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='was_delete',
            field=models.BooleanField(default=False),
        ),
    ]
