# Generated by Django 5.2.4 on 2025-10-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_contract_was_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='was_delete',
            field=models.BooleanField(default=False),
        ),
    ]
