MOVIMENTATION_STATUS_MAP = {
    'EM_ESTOQUE' : 'ENTRADA',
    'ATIVO' : 'SAIDA',
    'EM_TRANFERENCIA' : 'SAIDA'
}


STATUS_TO_MOV_CODE = {
    'EM_ESTOQUE': 'ENTRADA',
    'ATIVO': 'SAIDA',
    'EM_TRANSFERENCIA': 'SAIDA',
}