# Generated by Django 5.2.1 on 2025-05-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_item_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(unique=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=20, unique=True, verbose_name='Tipo da nota')),
            ],
        ),
        migrations.CreateModel(
            name='Item_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=25, unique=True, verbose_name='Nome do Item')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Link da Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='Numero da nota')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizaddo em')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='contract.proposal', verbose_name='Numero da Proposta')),
                ('invoice_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='invoice.invoice_type', verbose_name='Tipo da nota')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo unitário')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizaddo em')),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoice.invoice', verbose_name='Numero da nota')),
                ('status_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='invoice.invoice_item_status', verbose_name='Status do item')),
                ('name_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='invoice.item_catalog', verbose_name='Nome do item')),
            ],
        ),
    ]
