# Generated by Django 5.2.1 on 2025-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='invoice_item',
            options={'verbose_name_plural': 'Itens da nota'},
        ),
        migrations.AlterModelOptions(
            name='invoice_item_status',
            options={'verbose_name_plural': 'Status dos Itens'},
        ),
        migrations.AlterModelOptions(
            name='invoice_type',
            options={'verbose_name_plural': 'Tipo da nota'},
        ),
        migrations.AlterModelOptions(
            name='item_catalog',
            options={'verbose_name_plural': 'Catalogo de Itens'},
        ),
    ]
