# Generated by Django 5.2.1 on 2025-06-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_options_alter_invoice_item_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='status_item',
        ),
        migrations.AlterModelOptions(
            name='invoice_type',
            options={'verbose_name_plural': 'Status dos Itens'},
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='is_registred',
            field=models.BooleanField(default=False, verbose_name='Cadastrado'),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='name_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='invoice.item_catalog', verbose_name='Nome do item'),
        ),
        migrations.DeleteModel(
            name='Invoice_item_status',
        ),
    ]
