# Generated by Django 5.2.1 on 2025-06-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_item_status_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice_type',
            options={'verbose_name_plural': 'Tipo da nota'},
        ),
    ]
