# Generated by Django 5.2.4 on 2025-08-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_proposal_contract'),
        ('invoice', '0005_invoice_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contract.proposal', verbose_name='Numero da Proposta'),
        ),
    ]
