# Generated by Django 5.2.4 on 2025-09-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_item',
            old_name='name_item',
            new_name='catalog_item',
        ),
    ]
