# Generated by Django 5.2.4 on 2026-01-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_name_item_invoice_item_catalog_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_catalog',
            name='img_url',
        ),
        migrations.AddField(
            model_name='item_catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_items/'),
        ),
    ]
